// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./.vitepress/vitepress/components/home.vue')['default']
    IBxsUpArrow: typeof import('~icons/bxs/up-arrow')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    IRudderDocExpand: typeof import('~icons/rudder-doc/expand')['default']
    IRudderDocLight: typeof import('~icons/rudder-doc/light')['default']
    IRudderDocRightArrow: typeof import('~icons/rudder-doc/right-arrow')['default']
    IRudderDocTeam: typeof import('~icons/rudder-doc/team')['default']
    IRudderDocTypescript: typeof import('~icons/rudder-doc/typescript')['default']
    IRudderDocUnexpand: typeof import('~icons/rudder-doc/unexpand')['default']
    IRudderDocVue: typeof import('~icons/rudder-doc/vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpSource: typeof import('./.vitepress/vitepress/components/demo/vp-source.vue')['default']
  }
}
