name: Doc Build and Deploy

on:
  push:
      tags:
        - v*(-doc)$
  pull_request:
    branches:
      - master


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: npm install && npm run build

      - name: GitHub Pages Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.JIAN_SHU }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: ./dist